-- ============================================================================
-- SIPD -- Seed: Catalogo de Temas S-99 (191 temas oficiais, 10 categorias)
-- ============================================================================
--
-- Contexto:
-- Popula a base global de Temas e Categorias com a relacao oficial S-99
-- (docs/anexos/S-99a_T.pdf), extraida via pdftotext -raw e validada:
-- numeracao 1-194 completa sem lacunas nem duplicatas, 7 entradas
-- "(Nao use.)" (numeros retirados/reservados oficialmente) excluidas,
-- resultando em 187 temas reais. Idempotente (ON CONFLICT DO NOTHING em
-- ambas as tabelas) -- seguro rodar de novo sem duplicar dados.
--
-- Corresponde ao escopo de dados da UC-CAT-007 (Importar Catalogo S-99),
-- que segue sem tela de importacao propria -- populado diretamente aqui
-- a pedido do usuario, mesmo padrao ja usado para o seed de estados/cidades.
--
-- Fontes: docs/anexos/S-99a_T.pdf
-- ============================================================================

-- 1. Categorias (idempotente — pula as que já existem por nome)
insert into public.categorias (nome) values
  ('BÍBLIA/DEUS'),
  ('EVANGELIZAÇÃO/MINISTÉRIO'),
  ('FAMÍLIA/JOVENS'),
  ('FÉ/ESPIRITUALIDADE'),
  ('MUNDO, NÃO FAZER PARTE DO'),
  ('PROVAÇÕES/PROBLEMAS'),
  ('QUALIDADES/PADRÕES CRISTÃOS'),
  ('REINO/PARAÍSO'),
  ('RELIGIÃO/ADORAÇÃO'),
  ('ÚLTIMOS DIAS/JULGAMENTO DE DEUS')
on conflict (nome) do nothing;

-- 2. Temas (idempotente — pula os que já existem por número; categoria
-- resolvida por nome via join, não por id fixo)
insert into public.temas (numero, titulo, categoria_id)
select v.numero, v.titulo, c.id
from (values
  ('4', 'Que provas temos de que Deus existe?', 'BÍBLIA/DEUS'),
  ('26', 'Você é importante para Deus?', 'BÍBLIA/DEUS'),
  ('37', 'Obedecer a Deus é mesmo a melhor coisa a fazer?', 'BÍBLIA/DEUS'),
  ('54', 'Fortaleça sua fé em Deus e em suas promessas', 'BÍBLIA/DEUS'),
  ('70', 'Por que Deus merece sua confiança?', 'BÍBLIA/DEUS'),
  ('76', 'Princípios bíblicos -- Podem nos ajudar a lidar com os problemas atuais?', 'BÍBLIA/DEUS'),
  ('80', 'Você baseia a sua esperança na ciência ou na Bíblia?', 'BÍBLIA/DEUS'),
  ('88', 'Por que viver de acordo com os padrões da Bíblia?', 'BÍBLIA/DEUS'),
  ('99', 'Por que podemos confiar no que a Bíblia diz?', 'BÍBLIA/DEUS'),
  ('101', 'Jeová é o "Grandioso Criador"', 'BÍBLIA/DEUS'),
  ('114', 'Apreço pelas maravilhas da criação de Deus', 'BÍBLIA/DEUS'),
  ('124', 'Razões para crer que a Bíblia é de autoria divina', 'BÍBLIA/DEUS'),
  ('133', 'Tem importância o que cremos sobre a nossa origem?', 'BÍBLIA/DEUS'),
  ('137', 'Ocorreram realmente os milagres da Bíblia?', 'BÍBLIA/DEUS'),
  ('139', 'Sabedoria divina num mundo científico', 'BÍBLIA/DEUS'),
  ('145', 'Quem é semelhante a Jeová, nosso Deus?', 'BÍBLIA/DEUS'),
  ('164', 'Será que Deus ainda está no controle?', 'BÍBLIA/DEUS'),
  ('169', 'Por que ser orientado pela Bíblia?', 'BÍBLIA/DEUS'),
  ('175', 'O que prova que a Bíblia é autêntica?', 'BÍBLIA/DEUS'),
  ('187', 'Por que um Deus amoroso permite a maldade?', 'BÍBLIA/DEUS'),
  ('17', 'Glorifique a Deus com tudo o que você tem', 'EVANGELIZAÇÃO/MINISTÉRIO'),
  ('63', 'Tem você espírito evangelizador?', 'EVANGELIZAÇÃO/MINISTÉRIO'),
  ('66', 'Você também vai participar na colheita?', 'EVANGELIZAÇÃO/MINISTÉRIO'),
  ('81', 'Quem está qualificado para fazer discípulos?', 'EVANGELIZAÇÃO/MINISTÉRIO'),
  ('5', 'Você pode ter uma família feliz!', 'FAMÍLIA/JOVENS'),
  ('13', 'Qual o ponto de vista de Deus sobre o sexo e o casamento?', 'FAMÍLIA/JOVENS'),
  ('27', 'Como construir um casamento feliz', 'FAMÍLIA/JOVENS'),
  ('28', 'Mostre respeito e amor no seu casamento', 'FAMÍLIA/JOVENS'),
  ('29', 'As responsabilidades e recompensas de ter filhos', 'FAMÍLIA/JOVENS'),
  ('30', 'Como melhorar a comunicação na família', 'FAMÍLIA/JOVENS'),
  ('104', 'Pais, vocês estão construindo com materiais à prova de fogo?', 'FAMÍLIA/JOVENS'),
  ('110', 'Deus vem primeiro na vida familiar bem-sucedida', 'FAMÍLIA/JOVENS'),
  ('113', 'Jovens -- Como vocês podem ter uma vida feliz?', 'FAMÍLIA/JOVENS'),
  ('118', 'Olhemos os jovens do ponto de vista de Jeová', 'FAMÍLIA/JOVENS'),
  ('146', 'Use a educação para louvar a Jeová', 'FAMÍLIA/JOVENS'),
  ('190', 'Como se cumprirá a promessa de perfeita felicidade familiar', 'FAMÍLIA/JOVENS'),
  ('1', 'Você conhece bem a Deus?', 'FÉ/ESPIRITUALIDADE'),
  ('9', 'Escute e faça o que a Bíblia diz', 'FÉ/ESPIRITUALIDADE'),
  ('16', 'Seja cada vez mais amigo de Jeová', 'FÉ/ESPIRITUALIDADE'),
  ('18', 'Faça de Jeová a sua fortaleza', 'FÉ/ESPIRITUALIDADE'),
  ('22', 'Você está usando bem o que Jeová lhe dá?', 'FÉ/ESPIRITUALIDADE'),
  ('31', 'Você tem consciência da sua necessidade espiritual?', 'FÉ/ESPIRITUALIDADE'),
  ('44', 'Como os ensinos de Jesus podem ajudar você?', 'FÉ/ESPIRITUALIDADE'),
  ('46', 'Fortaleça sua confiança em Jeová', 'FÉ/ESPIRITUALIDADE'),
  ('60', 'Você tem um objetivo na vida?', 'FÉ/ESPIRITUALIDADE'),
  ('67', 'Medite na Bíblia e nas criações de Jeová', 'FÉ/ESPIRITUALIDADE'),
  ('71', '`Mantenha-se desperto'' -- Por que e como?', 'FÉ/ESPIRITUALIDADE'),
  ('74', 'Os olhos de Jeová estão em todo lugar', 'FÉ/ESPIRITUALIDADE'),
  ('87', 'Qual é a sua relação com Deus?', 'FÉ/ESPIRITUALIDADE'),
  ('142', 'Por que refugiar-se em Jeová', 'FÉ/ESPIRITUALIDADE'),
  ('147', 'Confie que Jeová tem o poder para nos salvar', 'FÉ/ESPIRITUALIDADE'),
  ('149', 'O que significa "andar com Deus"?', 'FÉ/ESPIRITUALIDADE'),
  ('151', 'Jeová é "uma altura protetora" para seu povo', 'FÉ/ESPIRITUALIDADE'),
  ('158', 'Seja corajoso e confie em Jeová', 'FÉ/ESPIRITUALIDADE'),
  ('159', 'Como encontrar segurança num mundo perigoso', 'FÉ/ESPIRITUALIDADE'),
  ('166', 'Verdadeira fé -- O que é e como mostrar', 'FÉ/ESPIRITUALIDADE'),
  ('168', 'Você pode sentir-se seguro neste mundo atribulado!', 'FÉ/ESPIRITUALIDADE'),
  ('172', 'Que reputação você tem perante Deus?', 'FÉ/ESPIRITUALIDADE'),
  ('188', 'Você confia em Jeová?', 'FÉ/ESPIRITUALIDADE'),
  ('189', 'Ande com Deus e receba bênçãos para sempre', 'FÉ/ESPIRITUALIDADE'),
  ('192', 'Você está no caminho para a vida eterna?', 'FÉ/ESPIRITUALIDADE'),
  ('11', 'Imite a Jesus e não faça parte do mundo', 'MUNDO, NÃO FAZER PARTE DO'),
  ('25', 'Lute contra o espírito do mundo', 'MUNDO, NÃO FAZER PARTE DO'),
  ('33', 'Quando vai existir verdadeira justiça?', 'MUNDO, NÃO FAZER PARTE DO'),
  ('39', 'Jesus Cristo vence o mundo -- Como e quando?', 'MUNDO, NÃO FAZER PARTE DO'),
  ('51', 'Será que a verdade da Bíblia está mudando a sua vida?', 'MUNDO, NÃO FAZER PARTE DO'),
  ('53', 'Você pensa como Deus?', 'MUNDO, NÃO FAZER PARTE DO'),
  ('64', 'Você ama os prazeres ou a Deus?', 'MUNDO, NÃO FAZER PARTE DO'),
  ('79', 'Você vai escolher ser amigo de Deus?', 'MUNDO, NÃO FAZER PARTE DO'),
  ('97', 'Permaneçamos inculpes em meio a uma geração pervertida', 'MUNDO, NÃO FAZER PARTE DO'),
  ('107', 'Você está treinando bem a sua consciência?', 'MUNDO, NÃO FAZER PARTE DO'),
  ('115', 'Não caia nas armadilhas de Satanás', 'MUNDO, NÃO FAZER PARTE DO'),
  ('116', 'Escolha sabiamente com quem irá associar-se!', 'MUNDO, NÃO FAZER PARTE DO'),
  ('119', 'Por que é benéfico que os cristãos vivam separados do mundo', 'MUNDO, NÃO FAZER PARTE DO'),
  ('138', 'Viva com bom juízo num mundo depravado', 'MUNDO, NÃO FAZER PARTE DO'),
  ('160', 'Mantenha a identidade cristã!', 'MUNDO, NÃO FAZER PARTE DO'),
  ('167', 'Ajamos sabiamente num mundo insensato', 'MUNDO, NÃO FAZER PARTE DO'),
  ('178', 'Ande no caminho da integridade', 'MUNDO, NÃO FAZER PARTE DO'),
  ('179', 'Rejeite as fantasias do mundo, empenhe-se pelas realidades do Reino', 'MUNDO, NÃO FAZER PARTE DO'),
  ('183', 'Desvie seus olhos do que é fútil!', 'MUNDO, NÃO FAZER PARTE DO'),
  ('191', 'Como o amor e a fé vencem o mundo', 'MUNDO, NÃO FAZER PARTE DO'),
  ('32', 'Como lidar com as ansiedades da vida', 'PROVAÇÕES/PROBLEMAS'),
  ('50', 'Como sempre tomar as melhores decisões', 'PROVAÇÕES/PROBLEMAS'),
  ('57', 'Como suportar perseguição', 'PROVAÇÕES/PROBLEMAS'),
  ('65', 'Como podemos ser pacíficos num mundo cheio de ódio', 'PROVAÇÕES/PROBLEMAS'),
  ('73', 'Você tem "um coração sábio?"', 'PROVAÇÕES/PROBLEMAS'),
  ('93', 'Desastres naturais -- Quando vão acabar?', 'PROVAÇÕES/PROBLEMAS'),
  ('105', 'Somos consolados em todas as nossas tribulações', 'PROVAÇÕES/PROBLEMAS'),
  ('108', 'Você pode encarar o futuro com confiança!', 'PROVAÇÕES/PROBLEMAS'),
  ('117', 'Como vencer o mal com o bem', 'PROVAÇÕES/PROBLEMAS'),
  ('141', 'Quando terão fim os gemidos da criação humana?', 'PROVAÇÕES/PROBLEMAS'),
  ('143', 'Confie no Deus de todo consolo', 'PROVAÇÕES/PROBLEMAS'),
  ('177', 'Onde encontrar ajuda em tempos de aflição?', 'PROVAÇÕES/PROBLEMAS'),
  ('184', 'A morte é o fim de tudo?', 'PROVAÇÕES/PROBLEMAS'),
  ('186', 'Sirva em união com o povo feliz de Deus', 'PROVAÇÕES/PROBLEMAS'),
  ('194', 'Como a sabedoria de Deus nos ajuda', 'PROVAÇÕES/PROBLEMAS'),
  ('7', 'Imite a misericórdia de Jeová', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('10', 'Seja honesto em tudo', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('12', 'Deus quer que você respeite quem tem autoridade', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('14', 'Um povo puro e limpo honra a Jeová', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('15', '`Faça o bem a todos''', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('42', 'O amor pode vencer o ódio?', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('48', 'Seja leal a Deus mesmo quando for testado', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('68', '`Continuem a perdoar uns aos outros liberalmente''', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('69', 'Por que mostrar amor abnegado?', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('72', 'O amor identifica os cristãos verdadeiros', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('75', 'Mostre que você apoia o direito de Jeová governar', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('77', '"Sempre mostrem hospitalidade"', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('78', 'Sirva a Jeová com um coração alegre', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('100', 'Como fazer amizades fortes e verdadeiras', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('103', 'Como você pode ter a verdadeira alegria?', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('144', 'Uma congregação leal sob a liderança de Cristo', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('148', 'Você tem o mesmo conceito de Deus sobre a vida?', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('157', 'Como os verdadeiros cristãos adornam o ensino divino', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('165', 'Os valores de quem você preza?', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('171', 'Poderá viver em paz agora -- E para sempre!', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('185', 'Será que a verdade influencia sua vida?', 'QUALIDADES/PADRÕES CRISTÃOS'),
  ('19', 'Como você pode saber seu futuro?', 'REINO/PARAÍSO'),
  ('21', 'Dê valor ao seu lugar no Reino de Deus', 'REINO/PARAÍSO'),
  ('23', 'A vida tem objetivo', 'REINO/PARAÍSO'),
  ('24', 'Você encontrou "uma pérola de grande valor"?', 'REINO/PARAÍSO'),
  ('35', 'É possível viver para sempre? O que você precisa fazer?', 'REINO/PARAÍSO'),
  ('49', 'Será que um dia a Terra vai ser limpa?', 'REINO/PARAÍSO'),
  ('61', 'Nas promessas de quem você confia?', 'REINO/PARAÍSO'),
  ('62', 'Onde encontrar uma esperança real para o futuro?', 'REINO/PARAÍSO'),
  ('85', 'Boas notícias num mundo violento', 'REINO/PARAÍSO'),
  ('90', 'Faça o máximo para alcançar a verdadeira vida!', 'REINO/PARAÍSO'),
  ('91', 'A presença do Messias e seu domínio', 'REINO/PARAÍSO'),
  ('109', 'O Reino de Deus está próximo', 'REINO/PARAÍSO'),
  ('111', 'É possível que a humanidade seja completamente curada?', 'REINO/PARAÍSO'),
  ('120', 'Por que se submeter à regência de Deus agora', 'REINO/PARAÍSO'),
  ('130', 'A Terra permanecerá para sempre', 'REINO/PARAÍSO'),
  ('132', 'Ressurreição -- A vitória sobre a morte!', 'REINO/PARAÍSO'),
  ('154', 'O governo humano é pesado na balança', 'REINO/PARAÍSO'),
  ('162', 'Seja liberto deste mundo em escuridão', 'REINO/PARAÍSO'),
  ('170', 'Quem está qualificado para governar a humanidade?', 'REINO/PARAÍSO'),
  ('174', 'Quem se qualificará para entrar no novo mundo de Deus?', 'REINO/PARAÍSO'),
  ('180', 'A ressurreição -- Por que essa esperança deve ser real para você', 'REINO/PARAÍSO'),
  ('182', 'O que o Reino de Deus está fazendo por nós agora?', 'REINO/PARAÍSO'),
  ('3', 'Você está avançando com a organização unida de Jeová?', 'RELIGIÃO/ADORAÇÃO'),
  ('8', 'Viva para fazer a vontade de Deus', 'RELIGIÃO/ADORAÇÃO'),
  ('36', 'Será que a vida é só isso?', 'RELIGIÃO/ADORAÇÃO'),
  ('43', 'Tudo o que Deus nos pede é para o nosso bem', 'RELIGIÃO/ADORAÇÃO'),
  ('45', 'Continue andando no caminho que leva à vida', 'RELIGIÃO/ADORAÇÃO'),
  ('52', 'Quem é o seu Deus?', 'RELIGIÃO/ADORAÇÃO'),
  ('55', 'Você está fazendo um bom nome perante Deus?', 'RELIGIÃO/ADORAÇÃO'),
  ('56', 'Existe um líder em quem você pode confiar?', 'RELIGIÃO/ADORAÇÃO'),
  ('58', 'Quem são os verdadeiros seguidores de Cristo?', 'RELIGIÃO/ADORAÇÃO'),
  ('83', 'Será que os cristãos precisam obedecer aos Dez Mandamentos?', 'RELIGIÃO/ADORAÇÃO'),
  ('86', 'Como orar a Deus e ser ouvido por ele?', 'RELIGIÃO/ADORAÇÃO'),
  ('89', 'Quem tem sede da verdade, venha!', 'RELIGIÃO/ADORAÇÃO'),
  ('92', 'O papel da religião nos assuntos do mundo', 'RELIGIÃO/ADORAÇÃO'),
  ('94', 'A religião verdadeira atende às necessidades da sociedade humana', 'RELIGIÃO/ADORAÇÃO'),
  ('95', 'Não seja enganado pelo ocultismo!', 'RELIGIÃO/ADORAÇÃO'),
  ('96', 'O que vai acontecer com as religiões?', 'RELIGIÃO/ADORAÇÃO'),
  ('125', 'Por que a humanidade precisa de resgate', 'RELIGIÃO/ADORAÇÃO'),
  ('126', 'Quem se salvará?', 'RELIGIÃO/ADORAÇÃO'),
  ('127', 'O que acontece quando morremos?', 'RELIGIÃO/ADORAÇÃO'),
  ('128', 'É o inferno um lugar de tormento ardente?', 'RELIGIÃO/ADORAÇÃO'),
  ('129', 'O que a Bíblia diz sobre a Trindade?', 'RELIGIÃO/ADORAÇÃO'),
  ('134', 'Será que os cristãos precisam guardar o sábado?', 'RELIGIÃO/ADORAÇÃO'),
  ('135', 'A santidade da vida e do sangue', 'RELIGIÃO/ADORAÇÃO'),
  ('136', 'Será que Deus aprova o uso de imagens na adoração?', 'RELIGIÃO/ADORAÇÃO'),
  ('140', 'Quem é realmente Jesus Cristo?', 'RELIGIÃO/ADORAÇÃO'),
  ('155', 'Chegou a hora do julgamento de Babilônia?', 'RELIGIÃO/ADORAÇÃO'),
  ('161', 'Por que Jesus sofreu e morreu?', 'RELIGIÃO/ADORAÇÃO'),
  ('163', 'Por que temer o Deus verdadeiro?', 'RELIGIÃO/ADORAÇÃO'),
  ('173', 'Existe uma religião verdadeira do ponto de vista de Deus?', 'RELIGIÃO/ADORAÇÃO'),
  ('2', 'Você vai sobreviver aos últimos dias?', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('6', 'O Dilúvio dos dias de Noé e você', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('20', 'Chegou o tempo de Deus governar o mundo?', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('34', 'Você vai ser marcado para sobreviver?', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('38', 'Como você pode sobreviver ao fim do mundo?', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('40', 'O que vai acontecer em breve?', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('41', 'Fiquem parados e vejam como Jeová os salvará', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('84', 'Escapará do destino deste mundo?', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('98', '"A cena deste mundo está mudando"', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('102', 'Preste atenção à "palavra profética"', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('106', 'Arruinar a Terra provocará retribuição divina', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('121', 'Uma família mundial que será salva da destruição', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('150', 'Este mundo está condenado à destruição?', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('152', 'Armagedom -- Por que e quando?', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('153', 'Tenha bem em mente o "atemorizante dia"!', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('156', 'O Dia do Juízo -- Tempo de temor ou de esperança?', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('176', 'Quando haverá verdadeira paz e segurança?', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('181', 'Já é mais tarde do que você imagina?', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS'),
  ('193', 'Os problemas de hoje logo serão coisa do passado', 'ÚLTIMOS DIAS/JULGAMENTO DE DEUS')
) as v(numero, titulo, categoria_nome)
join public.categorias c on c.nome = v.categoria_nome
on conflict (numero) do nothing;